# s = set()
# n = input("Enter the number : " )
# s.add(int(n))
# n = input("Enter the number : " )
# s.add(int(n))
# n = input("Enter the number : " )
# s.add(int(n))
# n = input("Enter the number : " )
# s.add(int(n))
# n = input("Enter the number : " )
# s.add(int(n))
# n = input("Enter the number : " )
# s.add(int(n))
# n = input("Enter the number : " )
# s.add(int(n))

# print(s)

s = {8, 7, 12, "Harry", [1,2]}
print(s)
